# Generated by Django 4.2.1 on 2023-06-17 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=45)),
                ("content", models.CharField(max_length=45)),
                ("created_at", models.DateTimeField()),
                ("left_day", models.IntegerField()),
                (
                    "nickname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="nickname",
                    ),
                ),
            ],
            options={
                "db_table": "post",
            },
        ),
    ]
