# Generated by Django 4.2.2 on 2023-06-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=45)),
                ("content", models.CharField(max_length=45)),
                ("created_at", models.DateTimeField()),
                ("left_day", models.IntegerField()),
            ],
            options={
                "db_table": "post",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("phone_number", models.CharField(max_length=45)),
                ("name", models.CharField(max_length=45)),
                ("address", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
