# Generated by Django 4.2.1 on 2023-06-22 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_url", models.URLField()),
                ("product_top_category", models.CharField(max_length=255)),
                ("product_mid_category", models.CharField(max_length=255)),
                ("product_low_category", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("address_city", models.CharField(max_length=255)),
                ("address_district", models.CharField(max_length=255)),
                ("address_dong", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expired_date", models.DateTimeField()),
                ("is_sharing", models.BooleanField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
