# Generated by Django 4.2.1 on 2023-06-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.AutoField(
                db_column="post_id", primary_key=True, serialize=False
            ),
        ),
    ]
