# Generated by Django 4.2.2 on 2023-06-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("comment", models.CharField(max_length=45)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "comment",
                "managed": False,
            },
        ),
    ]
