# Generated by Django 4.2.2 on 2023-06-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Post", "0002_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
