# Generated by Django 4.2.1 on 2023-06-17 19:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0003_remove_post_nickname_post_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.AddField(
            model_name="post",
            name="nickname",
            field=models.ForeignKey(
                default=datetime.datetime(
                    2023, 6, 17, 19, 47, 29, 433671, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
