# Generated by Django 4.2.1 on 2023-06-20 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Comment_id",
            new_name="comment_id",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="Post",
            new_name="post",
        ),
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="post.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
