# Generated by Django 4.2.1 on 2023-06-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_post_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_sharing",
            field=models.BooleanField(default=False),
        ),
    ]
