# Generated by Django 4.2.1 on 2023-06-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_post_is_sharing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user_id",
            new_name="user",
        ),
    ]
