# Generated by Django 4.2.1 on 2023-06-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_rename_reply_reply_reply_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
