# Generated by Django 4.2.1 on 2023-06-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0015_alter_comment_post_alter_commentreport_comment_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commentreport",
            unique_together=set(),
        ),
    ]
