# Generated by Django 4.2.1 on 2023-06-23 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0016_alter_commentreport_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="commentreport",
            unique_together={("comment", "user")},
        ),
    ]
