# Generated by Django 4.2.1 on 2023-06-23 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0017_post_comments_count_post_likes_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reply",
            fields=[
                ("reply_id", models.AutoField(primary_key=True, serialize=False)),
                ("reply", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.comment"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reply",
            },
        ),
    ]
