# Generated by Django 4.2.1 on 2023-06-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0022_mysharinglist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MySharingList",
        ),
    ]
