# Generated by Django 4.2.1 on 2023-06-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0023_delete_mysharinglist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FavoritePost",
        ),
    ]
