# Generated by Django 4.2.1 on 2023-06-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0024_delete_favoritepost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_sharing",
            field=models.IntegerField(default=0),
        ),
    ]
