channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.1.2
- pip:
  - mlflow==2.4
  - astunparse==1.6.3
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - matplotlib==3.7.1
  - opencv-contrib-python==4.7.0.72
  - opencv-python-headless==4.7.0.72
  - opencv-python==4.7.0.72
  - opt-einsum==3.3.0
  - pathlib==1.0.1
  - psutil==5.9.5
  - pydot==1.4.2
  - pyyaml==6.0
  - scipy==1.10.1
  - torch==2.0.1
  - torchvision==0.15.2
  - tqdm==4.65.0
  - ultralytics==8.0.120
name: mlflow-env
