# Generated by Django 4.2.1 on 2023-06-26 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                ("disposal_location", models.CharField(max_length=100, null=True)),
                ("postal_code", models.CharField(max_length=10)),
                ("address_road", models.CharField(max_length=100)),
                ("address_land", models.CharField(max_length=100)),
                ("address_district", models.CharField(max_length=100)),
                ("address_dong", models.CharField(max_length=100)),
                ("address_city", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
