# Generated by Django 4.2.1 on 2023-06-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_rename_id_user_used_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="used_id",
            new_name="id",
        ),
    ]
