# Generated by Django 4.2.1 on 2023-06-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_rename_used_id_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="id",
            new_name="user_id",
        ),
    ]
