# Generated by Django 4.2 on 2023-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WasteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_image",
                    models.ImageField(default="media/testt.jpg", upload_to=""),
                ),
                (
                    "output_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="output_images/"
                    ),
                ),
            ],
        ),
    ]
