# Generated by Django 4.2 on 2023-06-28 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteSpec",
            fields=[
                ("waste_spec_id", models.AutoField(primary_key=True, serialize=False)),
                ("index_large_category", models.IntegerField()),
                ("index_small_category", models.IntegerField()),
                ("city", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("top_category", models.CharField(max_length=50)),
                ("large_category", models.CharField(max_length=50)),
                ("small_category", models.CharField(max_length=50)),
                ("size_range", models.CharField(max_length=50, null=True)),
                ("is_exists_small_cat_model", models.BooleanField(default=True)),
                ("type", models.CharField(max_length=50)),
                ("fee", models.IntegerField()),
            ],
            options={
                "db_table": "waste_spec",
            },
        ),
        migrations.CreateModel(
            name="UrlImages",
            fields=[
                ("waste_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_title", models.TextField(default="testt.jpg", null=True)),
                ("image_url", models.TextField(default="media/testt.jpg")),
                ("apply_binary", models.IntegerField(default=0)),
                ("postal_code", models.CharField(max_length=255, null=True)),
                ("address_full_lend", models.CharField(max_length=255, null=True)),
                ("address_full_street", models.CharField(max_length=255, null=True)),
                ("address_city", models.CharField(max_length=255, null=True)),
                ("address_district", models.CharField(max_length=255, null=True)),
                ("address_dong", models.CharField(max_length=255, null=True)),
                ("address_detail", models.CharField(max_length=255, null=True)),
                ("disposal_location", models.CharField(max_length=255, null=True)),
                ("disposal_datetime", models.CharField(max_length=255, null=True)),
                ("memo", models.CharField(max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waste_spec_id",
                    models.ForeignKey(
                        db_column="waste_spec_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waste.wastespec",
                    ),
                ),
            ],
            options={
                "db_table": "url_images",
            },
        ),
    ]
