# Generated by Django 4.2 on 2023-06-26 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UrlImages",
            fields=[
                ("waste_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_title", models.TextField(default="testt.jpg", null=True)),
                ("image_url", models.TextField(default="media/testt.jpg")),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "url_images",
            },
        ),
    ]
