# Generated by Django 4.2 on 2023-06-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreprocessedImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_title", models.TextField(default="testt.jpg", null=True)),
                ("image_path", models.FilePathField(default="media/testt.jpg")),
                ("image_context", models.TextField(default="일방통행")),
            ],
            options={
                "db_table": "preprocessed_images",
            },
        ),
        migrations.DeleteModel(
            name="WasteInfo",
        ),
    ]
