channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=22.0.2
- pip:
  - mlflow==2.4
  - astunparse==1.6.3
  - cloudpickle==2.2.1
  - ipython==8.14.0
  - matplotlib==3.7.1
  - numpy==1.23.5
  - opt-einsum==3.3.0
  - pyyaml==5.4.1
  - requests==2.31.0
  - torch==2.0.1
  - ultralytics==8.0.119
name: mlflow-env
