# Generated by Django 4.2.1 on 2023-06-25 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0024_delete_favoritepost"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoritePost",
            fields=[
                (
                    "favorite_post_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "favorite_post",
            },
        ),
    ]
